"""
Purpose
-------
Primary application orchestrator for the Multi-Command Execution Engine (Phase 2).

Responsibilities
----------------
- Accept an InvestigationPlan domain object.
- Inspect execution_strategy (SEQUENTIAL vs PARALLEL).
- Delegate execution to SequentialRunner or ParallelRunner.
- Calculate aggregated ExecutionMetrics.
- Return standardized InvestigationExecutionResult for downstream correlation.

Does NOT
---------
- Perform RCA or LLM reasoning.
- Modify InvestigationPlan objects.
"""

from datetime import datetime
import time
from typing import Optional

from domain.execution.models import (
    ExecutionMetrics,
    ExecutionStatus,
    InvestigationExecutionResult,
)
from domain.investigation.models import ExecutionStrategy, InvestigationPlan

from .parallel_runner import ParallelRunner
from .sequential_runner import SequentialRunner


class ExecutionService:
    """
    Main Phase 2 Application Service orchestrating multi-command investigation executions.
    """

    def __init__(
        self,
        sequential_runner: Optional[SequentialRunner] = None,
        parallel_runner: Optional[ParallelRunner] = None,
    ):
        self.sequential_runner = sequential_runner or SequentialRunner()
        self.parallel_runner = parallel_runner or ParallelRunner()

    def execute_plan(self, plan: InvestigationPlan) -> InvestigationExecutionResult:
        """
        Executes all steps in an InvestigationPlan and returns an InvestigationExecutionResult.

        Parameters
        ----------
        plan : InvestigationPlan
            Plan generated by Phase 1 InvestigationPlanner.

        Returns
        -------
        InvestigationExecutionResult
            Standardized execution results container passed to Phase 3.
        """
        start_time = time.time()
        executed_at = datetime.utcnow()

        if not plan.steps:
            metrics = ExecutionMetrics(
                total_steps=0,
                successful_steps=0,
                failed_steps=0,
                skipped_steps=0,
                total_duration_seconds=0.0,
                strategy_used=plan.execution_strategy.value,
            )
            return InvestigationExecutionResult(
                investigation_id=plan.investigation_id,
                user_question=plan.user_question,
                status=ExecutionStatus.SUCCESS,
                metrics=metrics,
                step_results=[],
                executed_at=executed_at,
                metadata={"matched_template": plan.metadata.get("matched_template", "unknown")},
            )

        # Select runner strategy
        if plan.execution_strategy == ExecutionStrategy.PARALLEL:
            step_results = self.parallel_runner.run(plan.steps)
        else:
            step_results = self.sequential_runner.run(plan.steps)

        total_duration = round(time.time() - start_time, 3)

        # Calculate metrics
        total = len(step_results)
        successful = sum(1 for r in step_results if r.status == ExecutionStatus.SUCCESS)
        failed = sum(1 for r in step_results if r.status in (ExecutionStatus.FAILED, ExecutionStatus.TIMEOUT))
        skipped = sum(1 for r in step_results if r.status == ExecutionStatus.SKIPPED)

        if failed == 0:
            overall_status = ExecutionStatus.SUCCESS
        elif successful > 0:
            overall_status = ExecutionStatus.PARTIAL_SUCCESS
        else:
            overall_status = ExecutionStatus.FAILED

        metrics = ExecutionMetrics(
            total_steps=total,
            successful_steps=successful,
            failed_steps=failed,
            skipped_steps=skipped,
            total_duration_seconds=total_duration,
            strategy_used=plan.execution_strategy.value,
        )

        return InvestigationExecutionResult(
            investigation_id=plan.investigation_id,
            user_question=plan.user_question,
            status=overall_status,
            metrics=metrics,
            step_results=step_results,
            executed_at=executed_at,
            metadata={
                "matched_template": plan.metadata.get("matched_template", "unknown"),
                "engine_version": "2.0.0",
            },
        )
