"""
Purpose:
--------
Represents the Investigation domain data models using Pydantic.

Responsibilities:
-----------------
- Define schema for InvestigationPlan and InvestigationStep.
- Enforce strict typing and validation for investigation metadata.

Does NOT:
---------
- Execute SSH commands.
- Call LLM APIs.
- Parse terminal stdout strings.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional
from uuid import uuid4

from pydantic import BaseModel, Field


class InvestigationPriority(str, Enum):
    """Priority level assigned to an investigation plan."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class InvestigationStatus(str, Enum):
    """Lifecycle status of an investigation plan."""
    PENDING = "PENDING"
    PLANNED = "PLANNED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ExecutionStrategy(str, Enum):
    """Execution strategy determining how investigation steps should run."""
    SEQUENTIAL = "SEQUENTIAL"
    PARALLEL = "PARALLEL"


class InvestigationStep(BaseModel):
    """
    Represents a single observation/diagnostic step within an investigation plan.
    """

    step_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for the investigation step."
    )

    order: int = Field(
        ...,
        ge=1,
        description="Execution sequence order within the plan."
    )

    command_id: str = Field(
        ...,
        description="Whitelisted command key matching the command registry."
    )

    description: str = Field(
        ...,
        description="Human-readable explanation of why this step is conducted."
    )

    parser_name: str = Field(
        ...,
        description="Name of the parser function expected to process the raw output."
    )

    timeout_seconds: int = Field(
        default=30,
        ge=1,
        description="Maximum allowed execution time in seconds."
    )

    depends_on: List[str] = Field(
        default_factory=list,
        description="List of step_ids that must complete before this step runs."
    )


class InvestigationPlan(BaseModel):
    """
    Complete investigation plan object generated by the Investigation Planner.
    """

    investigation_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique identifier for the investigation plan."
    )

    user_question: str = Field(
        ...,
        min_length=1,
        description="Original natural language question asked by the user."
    )

    priority: InvestigationPriority = Field(
        default=InvestigationPriority.MEDIUM,
        description="Assigned priority for this investigation."
    )

    status: InvestigationStatus = Field(
        default=InvestigationStatus.PLANNED,
        description="Current state of the investigation."
    )

    execution_strategy: ExecutionStrategy = Field(
        default=ExecutionStrategy.SEQUENTIAL,
        description="Strategy for executing the investigation steps."
    )

    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC timestamp when the plan was generated."
    )

    estimated_duration_seconds: Optional[int] = Field(
        default=None,
        description="Estimated total time required to execute all steps."
    )

    steps: List[InvestigationStep] = Field(
        default_factory=list,
        description="List of diagnostic steps comprising the investigation."
    )

    metadata: Dict[str, str] = Field(
        default_factory=dict,
        description="Additional context metadata or tags."
    )
